"""baseline_existing_tables

Revision ID: c3af57774955
Revises: 
Create Date: 2026-04-03 21:07:43.723982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3af57774955'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_index(op.f('ix_agent_exp_intent_score'), table_name='agent_experiences')
    op.drop_index(op.f('ix_agent_exp_session_ts'), table_name='agent_experiences')
    op.drop_index(op.f('ix_agent_experiences_agent_intent'), table_name='agent_experiences')
    op.drop_index(op.f('ix_agent_experiences_id'), table_name='agent_experiences')
    op.drop_index(op.f('ix_agent_experiences_session_id'), table_name='agent_experiences')
    op.drop_index(op.f('ix_agent_experiences_timestamp'), table_name='agent_experiences')
    op.drop_table('agent_experiences')
    op.create_index(op.f('ix_security_events_attack_score'), 'security_events', ['attack_score'], unique=False)
    op.create_index(op.f('ix_security_events_bot_score'), 'security_events', ['bot_score'], unique=False)
    op.create_index(op.f('ix_security_rules_external_id'), 'security_rules', ['external_id'], unique=False)
    op.create_index(op.f('ix_security_rules_rule_pack_id'), 'security_rules', ['rule_pack_id'], unique=False)
    op.create_foreign_key(None, 'security_rules', 'rule_packs', ['rule_pack_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'security_rules', type_='foreignkey')
    op.drop_index(op.f('ix_security_rules_rule_pack_id'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_external_id'), table_name='security_rules')
    op.drop_index(op.f('ix_security_events_bot_score'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_attack_score'), table_name='security_events')
    op.create_table('agent_experiences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('user_message', sa.TEXT(), nullable=False),
    sa.Column('agent_intent', sa.VARCHAR(length=32), nullable=False),
    sa.Column('agent_response', sa.TEXT(), nullable=False),
    sa.Column('tools_used', sa.TEXT(), nullable=True),
    sa.Column('tool_call_count', sa.INTEGER(), nullable=True),
    sa.Column('suggested_actions', sa.TEXT(), nullable=True),
    sa.Column('feedback_score', sa.INTEGER(), nullable=True),
    sa.Column('feedback_text', sa.TEXT(), nullable=True),
    sa.Column('feedback_at', sa.DATETIME(), nullable=True),
    sa.Column('keywords', sa.TEXT(), nullable=True),
    sa.Column('steps_taken', sa.INTEGER(), nullable=True),
    sa.Column('response_length', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_experiences_timestamp'), 'agent_experiences', ['timestamp'], unique=False)
    op.create_index(op.f('ix_agent_experiences_session_id'), 'agent_experiences', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_experiences_id'), 'agent_experiences', ['id'], unique=False)
    op.create_index(op.f('ix_agent_experiences_agent_intent'), 'agent_experiences', ['agent_intent'], unique=False)
    op.create_index(op.f('ix_agent_exp_session_ts'), 'agent_experiences', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_agent_exp_intent_score'), 'agent_experiences', ['agent_intent', 'feedback_score'], unique=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
